<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = ['holdings' => []];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<? if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<? endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("hold_login")?></a>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEsc('request_place_text')?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>

<? if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><? endif; ?>

<?
   $noHoldingsMessage = '';
   $numHoldings = count($holdings['holdings']);
   if ($numHoldings < 1) {
      $noHoldingsMessage = 'The catalog cannot display location or copy information at this time. Please ask a library staff member for assistance.';
   }
?>

<? 
// CARLI EDIT: Split each holding by MFHD_ID. Do not group together by Location Name.
$split = array();
$split['blocks'] = $holdings['blocks'];
$new_holding_id = '';
$last_holding_id = '';

// MFHDs are already sorted by institution.
// We want to sort by location, too, but also preserving institution order
// Therefore, our sort_by key will be prefixed with the insitution count number (padded w/ zeroes)
$inst_count = 0;
$last_inst = '';
foreach ($holdings['holdings'] as $location => $location_val) {

    // keep track of institution count (used for sort_by key)
    if (preg_match('/\|/', $location)) {
        $loc_in_parts = explode("|", $location);
        $inst = $loc_in_parts[0];
        $loc = $loc_in_parts[1];
    } else {
        $inst = ' ';
        $loc = $location;
    }
    if ($inst != $last_inst) {
        $inst_count++;
        $last_inst = $inst;
    }

    // only display the first set of eresource data (i.e., one set per MFHD, not every ITEM)
    $eresource_per_mfhd = array();

    foreach ($location_val['items'] as $itm) {
        // Cite this/Text this/etc. requires callnumber; if one doesn't exist, use a dummy value
        if (!isset($itm['callnumber'])) {
            $itm['callnumber'] = 'N/A';
        }
        $new_holding_id = $location . '|' . $itm['id'] . '|' . $itm['holdings_id'];
        if ($new_holding_id != $last_holding_id) {
            $last_holding_id = $new_holding_id;
            // Notes and Summary need special care:
            if (isset($itm['notes'])) { 
                $notes = array();
                if (! is_array($itm['notes'])) {
                    $notes[] = $itm['notes'];
                } else {
                    $notes = $itm['notes'];
                }
                $split['holdings'][$new_holding_id]['textfields']['holdings_notes'] = $notes;
            }
            if (isset($itm['summary'])) { 
                $sum = array();
                if (! is_array($itm['summary'])) {
                    $sum[] = $itm['summary'];
                } else {
                    $sum = $itm['summary'];
                }
                $split['holdings'][$new_holding_id]['textfields']['summary'] = $sum;
            }
        }
        // sort by location (preserving institution order)
        $split['holdings'][$new_holding_id]['sort_by'] = sprintf('%03d', $inst_count) . $loc;

        // only display the first set of eresource data (i.e., one set per MFHD, not every ITEM)
        if (count($itm['eresource']) > 0) {
            if (array_key_exists($itm['holdings_id'], $eresource_per_mfhd)) {
                $eresource_per_mfhd[$itm['holdings_id']]++;
            } else {
                $eresource_per_mfhd[$itm['holdings_id']] = 1;
            }
        }
        if (array_key_exists($itm['holdings_id'], $eresource_per_mfhd) && $eresource_per_mfhd[$itm['holdings_id']] > 1) {
            $itm['eresource'] = array(); // clear it out
        }

        $split['holdings'][$new_holding_id]['items'][] = $itm;
        $split['holdings'][$new_holding_id]['location'] = $holdings['holdings'][$location]['location'];
        $split['holdings'][$new_holding_id]['locationhref'] = $holdings['holdings'][$location]['locationhref'];

    }
}
$holdings = $split;
if (array_key_exists('holdings', $holdings) && count($holdings) > 0) {
    usort($holdings['holdings'], function($a, $b) { return strcmp($a['sort_by'], $b['sort_by']); });
} else {
    $holdings['holdings'] = array();
}
?>

<!--
<pre>
<?  
//print_r($holdings);
?>
</pre>
-->


<! CARLI BEGIN 'Request First Available' !>
<?
  $rfaScript = <<<JS
$(document).ready(function() {

  //global: now defined in js/check_requestable.js
  //var vol2Bibs = [];

JS
?>
<?
// https://defuse.ca/blog/escaping-string-literals-for-javascript-in-php.html
function js_string_escape($data)
{
    $safe = "";
    for($i = 0; $i < strlen($data); $i++)
    {
        if(ctype_alnum($data[$i]))
            $safe .= $data[$i];
        else
            $safe .= sprintf("\\x%02X", ord($data[$i]));
    }
    return $safe;
}
$atLeastOneAvailableItem = false;
$volNumsArr = array();
$holdingsCount = count($holdings['holdings']);
$rfaScript .= "  vol2BibsHoldings = " . $holdingsCount . ";\n";
if ($user) {
    $rfaScript .= "  patronHomeLibrary = '" . explode('.', $user->cat_username)[0] . "';\n";
} else {
    $rfaScript .= "  patronHomeLibrary = '';\n";
}
foreach ($holdings['holdings'] as $location => $location_val) {
    foreach ($location_val['items'] as $itm) {
        // if any single item has 'availability', then we can assume callslip is allowed
        if (array_key_exists('availability', $itm) && $itm['availability']) {
            $atLeastOneAvailableItem = true;
        }
        if (array_key_exists('volume', $itm) && array_key_exists('item_id', $itm)
        && strlen($itm['volume']) > 0  && strlen($itm['item_id']) > 0
        ) {
            if (! $itm['availability']) {
                continue;
            }
            $vol = $itm['volume'];

            if (! array_key_exists($vol, $volNumsArr)) {
                $volNumsArr[$vol] = 1;
                $rfaScript .= "  vol2Bibs['" . js_string_escape($vol) . "'] = [];\n";
            }
            $rfaScript .= "  vol2Bibs['" . js_string_escape($vol) . "'].push('" . js_string_escape($itm['id']) . "." . js_string_escape($itm['item_id']) . "');\n";

        }
    }
}
uksort($volNumsArr,
    function ($a, $b) {
        $numeric_a = $a;
        $numeric_b = $b;
        if (preg_match('/^[^\d]*(\d+)/', $numeric_a, $matches)) {
            $numeric_a = $matches[1];
        } else {
            $numeric_a = 99999999;
        }
        if (preg_match('/^[^\d]*(\d+)/', $numeric_b, $matches)) {
            $numeric_b = $matches[1];
        } else {
            $numeric_b = 99999999;
        }
        return ($numeric_a > $numeric_b);
    }
);
?>
<?
  $rfaScript .= <<<JS
  //console.log(vol2Bibs);

});
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $rfaScript, 'SET'); ?>
<br/>
<? if ($atLeastOneAvailableItem): ?>
 <? if (!$user || !$user->cat_username): ?>
  <? if (getenv('VUFIND_LIBRARY_IS_UC')): ?>
    <div id="checkRequestableStatus">
    </div>
    <form class="form-inline">
      <input data-toggle="modal" data-target="#mustBeLoggedInFirst" class="btn btn-primary" type="button" value="Request from I-Share Libraries"></input>
    </form>
  <? else: ?>
    <div id="checkRequestableStatus">
    </div>
    <form class="form-inline">
      <input data-toggle="modal" data-target="#mustBeLoggedInFirst" class="btn btn-primary" type="button" value="Request Item"></input>
    </form>
  <? endif; ?>
 <? else: ?>
    <form class="form-inline">
    <hr>
  <? if (count($volNumsArr) > 1 && $holdingsCount > 1) : ?>
    <label class="control-label"><?=$this->translate('carli_rfa_select_item_label', [], 'Select Item(s):')?></label>
    <select class="form-control" id="checkRequestableItem" size="<?= count($volNumsArr) < 5 ? count($volNumsArr) : 5?>" multiple="multiple">
    <?
      echo "<option value=\"\" selected>any item</option>\n";
      foreach ($volNumsArr as $volNum => $ignore) {
          echo '<option value="' . $volNum . '">' . $volNum . "</option>\n";
      }
    ?>
     </select>
  <? endif; ?>
  <? if (getenv('VUFIND_LIBRARY_IS_UC')): ?>
     <input class="btn btn-primary" type="button" onClick="checkRequestableItems()" value="Request from I-Share Libraries" id="requestFirstAvailableButton"></input>
  <? else: ?>
     <input class="btn btn-primary" type="button" onClick="checkRequestableItems()" value="Request Item" id="requestFirstAvailableButton"></input>
  <? endif; ?>
  <br>
  </form>
  <div id="checkRequestableStatus">
  </div>
  <hr>
 <? endif; ?>
<? endif; ?>
<! CARLI END 'Request First Available' !>


<? foreach ($holdings['holdings'] as $holding): ?>
<h3>
<! CARLI BEGIN libname !>
<?
    if (array_key_exists('item_agency_id', $holding['items'][0])) {
       $this->libname = $holding['items'][0]['item_agency_id'];
       if ($this->lastLibname != $this->libname) {
           echo $this->translate($this->libname);
       }
       $this->lastLibname = $this->libname;
    } else {
       $this->libname = $holding['location'];
       if ($this->lastLibname != $this->libname) {
           echo $this->translate($this->libname);
       }
       $this->lastLibname = $this->libname;
    }
?>
<! CARLI END libname !>
</h3>
<! CARLI BEGIN locationText !>
<h4 class='location'>
  <? $locationText = isset($holding['location']) ? $this->transEsc('location_' . $holding['location'], [], $holding['location']) : ''; ?>
  <? if (isset($holding['locationhref']) && $holding['locationhref']): ?>
    <strong>Location:</strong> <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
  <? else: ?>
    <strong>Location:</strong> <?=$locationText?>
  <? endif; ?>
</h4>
<! CARLI END locationText !>
<!-- CARLI BEGIN comment-out original table
<table class="table table-striped" summary="<?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?>">
CARLI END comment-out original table -->
<!-- CARLI BEGIN custom table -->
<table class="carli-holdings-unit table table-striped" data-carli-display="5" summary="<?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?>">
<!-- CARLI END custom table -->
  <? $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
  <!-- CARLI EDIT: don't show dummy (N/A) call numbers -->
  <? 
     $numCallNos = 0;
     foreach ($callNos as $callNo) {
       if ($callNo != 'N/A') {
         $numCallNos++;
       }
     }
  ?>
   <? if ($numCallNos > 0): ?>
  <tr>
    <th><?=$this->transEsc("Call Number")?>: </th>
    <td width="50%">
      <? foreach ($callNos as $callNo): ?>
        <? if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
        <? else: ?>
          <?=$this->escapeHtml($callNo)?>
        <? endif; ?>
        <br />
      <? endforeach; ?>
    </td>
  </tr>
   <? endif; ?>
  <? endif; ?>
  <? if (isset($holding['textfields'])): foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
    <tr>
      <? // Translation for summary is a special case for backwards-compatibility ?>
      <th><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
      <td>
        <? foreach ($textFields as $current): ?>
          <?=$this->escapeHtml($current)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endforeach; endif; ?>
  <?
       $ph_last_id = '';
       $ph_last_holdings_id = '';
  ?>
  <? foreach ($holding['items'] as $row): ?>
<! CARLI BEGIN fixrequestlink !>
<?
    if (isset($row['ILLRequestLink'])) {
        if (isset($row['ILLRequestLink']['query'])) {
            $row['ILLRequestLink']['query'] = 'item_id=' . $row['item_id'] . '&' . $row['ILLRequestLink']['query'];
        }
    }
?>
<! CARLI END fixrequestlink !>
<! CARLI BEGIN eresource !>
<?
   if (array_key_exists('eresource', $row)) {
       $er_cnt = count($row['eresource']);
       if ($er_cnt > 0) {
          for($er_cnt = 0; $er_cnt < count($row['eresource']); ++$er_cnt) {
              $er_hyperlink_text = $row['eresource'][$er_cnt];
              if (array_key_exists('eresource_hyperlink_text', $row) && $row['eresource_hyperlink_text'][$er_cnt]) {
                  $er_hyperlink_text = $row['eresource_hyperlink_text'][$er_cnt];
              }
              $er_text = '';
              if (array_key_exists('eresource_text', $row) && $row['eresource_text'][$er_cnt]) {
                  $er_text = ' ' . $row['eresource_text'][$er_cnt];
              }
              echo '<tr><th>' . $row['eresource_label'][$er_cnt] . '</th><td><a href="' . $row['eresource'][$er_cnt] . '">' . $er_hyperlink_text . "</a>" . $er_text . "</td></tr>\n";
          }
       }
   }
?>
<! CARLI END eresource !>
    <?
      // AJAX Check record?
      $check = isset($row['check']) && $row['check'];
      $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
      $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
// CARLI BEGIN force checkILLRequest = false
      // Setting this to false will prevent the 'Check Requestability' Ajax calls, which are extremely resource intensive!!!
      $checkILLRequest = true;
// CARLI END force checkILLRequest = false
    ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
      <tr vocab="http://schema.org/" typeof="Offer">
        <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <link property="availability" href="http://schema.org/InStoreOnly" />
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest ' : ''?>placehold" <? if (!empty($row['linkLightbox'])): ?>data-lightbox <? endif; ?>href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
              <? endif; ?>
              <? if (isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <? endif; ?>
              <? if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>


                <!-- CARLI EDIT: if user not logged in, throw up modal dialog warning -->
                <? if ($user): ?>
                  <a hiddenId="<?=$row['id']?>" class="ajaxCheckRequestableItem <?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox hiddenHref="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
                <? else: ?>
                  <a data-toggle="modal" data-target="#mustBeLoggedInFirst" hiddenId="<?=$row['id']?>" hiddenHref="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
                <? endif; ?>

              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="text-danger"><?=$this->transEsc($row['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <a class="<?=$check ? 'checkRequest' : ''?> placehold" <? if (!empty($row['linkLightbox'])): ?>data-lightbox <? endif; ?>href="<?=$this->recordLink()->getRequestUrl($row['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              <? endif; ?>
            <? endif; ?>
            <? if (isset($row['item_notes'])): ?>
              <div class="item-notes">
                <b><?=$this->transEsc("Item Notes")?>:</b>
                <ul>
                  <? foreach ($row['item_notes'] as $item_note): ?>
                    <li><?=$this->escapeHtml($item_note) ?></li>
                  <? endforeach; ?>
                </ul>
              </div>
            <? endif; ?>
          <? endif; ?>
          <? /* Embed item structured data: library, barcode, call number */ ?>
          <? if ($row['location']): ?>
            <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
          <? endif; ?>
          <? if ($row['barcode']): ?>
            <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
          <? endif; ?>
          <? if ($row['callnumber']): ?>
            <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
          <? endif; ?>
          <? /* Declare that the item is to be borrowed, not for sale */ ?>
            <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
            <link property="itemOffered" href="#record" />
        </td>
      </tr>
    <? endif; ?>

  <!-- CARLI EDIT: embed purchase history -->
  <? if (!empty($row['purchase_history'])): ?>
  <? 
     if ($row['id'] != $ph_last_id && $row['holdings_id'] != $ph_last_holdings_id) {
       $ph_last_id = $row['id'];
       $ph_last_holdings_id = $row['holdings_id'];
  ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($row['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? 
      }
  ?>
  <? endif; ?>

  <? endforeach; ?>

<!-- CARLI: cite/text this/email this/export record/save to list -->
<? if (!empty($callNos)): ?>
  <? foreach ($callNos as $callNo): ?>
<tr><td colspan="2">
<ul class="record-nav nav nav-pills hidden-print">
  <? if (count($this->driver->getCitationFormats()) > 0): ?>
    <li><a class="cite-record" data-lightbox href="<?=$this->url('home')?>Record/<?=$this->escapeHtmlAttr($row['id'])?>/Cite" rel="nofollow"><i class="fa fa-asterisk" aria-hidden="true"></i> <?=$this->transEsc('Cite this')?></a></li>
  <? endif; ?>
  <? if ($this->accountCapabilities()->getSmsSetting() !== 'disabled'): ?>
    <li><a class="sms-record" data-lightbox href="<?=$this->url('home')?>Record/<?=$this->escapeHtmlAttr($row['id'])?>/SMS?callnumber=<?= $this->escapeHtmlAttr($callNo) ?>&location=<?= $this->escapeHtmlAttr($locationText) ?>" rel="nofollow"><i class="fa fa-mobile" aria-hidden="true"></i> <?=$this->transEsc('Text this')?></a></li>
  <? endif; ?>


  <li><a class="mail-record" data-lightbox href="<?=$this->url('home')?>Record/<?=$this->escapeHtmlAttr($row['id'])?>/Email?callnumber=<?= $this->escapeHtmlAttr($callNo) ?>&location=<?= $this->escapeHtmlAttr($locationText) ?>" rel="nofollow"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc('Email this')?></a></li>

    <li class="dropdown">
      <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->url('home')?>Record/<?=$this->escapeHtmlAttr($row['id'])?>/Export?callnumber=<?= $this->escapeHtmlAttr($callNo) ?>&location=<?= $this->escapeHtmlAttr($locationText) ?>" rel="nofollow"><i class="fa fa-list-alt" aria-hidden="true"></i> <?=$this->transEsc('Export Record') ?></a>
  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
      <ul class="dropdown-menu" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->url('home')?>Record/<?=$this->escapeHtmlAttr($row['id'])?>/Export?style=<?=$this->escapeHtmlAttr($exportFormat)?>&callnumber=<?= $this->escapeHtmlAttr($callNo) ?>&location=<?= $this->escapeHtmlAttr($locationText) ?>" rel="nofollow"><?=$this->transEsc('Export to')?> <?=$this->transEsc($this->export()->getLabelForFormat($exportFormat))?></a></li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>

      <li><a class="save-record" data-lightbox href="<?=$this->url('home')?>Record/<?=$this->escapeHtmlAttr($row['id'])?>/Save" rel="nofollow"><i class="fa fa-star" aria-hidden="true"></i> Save to List</a></li>
</ul>
</td></tr>
  <? endforeach; ?>
<? endif; ?>
<!-- END OF CARLI: cite/text this/email this/export record/save to list -->

  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
<? endforeach; ?>

<!-- CARLI: no MFHDs/holdings message -->
<? if (!empty($noHoldingsMessage)): ?>
<tr><td colspan="2"><?=$noHoldingsMessage?></td></tr>
<? endif; ?>

<!-- CARLI: no MFHDs/holdings message -->
<!--
<? if (!empty(getenv('CARLIDEBUG'))): ?>
<tr><td colspan="2"><?=getenv('CARLIDEBUG')?></td></tr>
<? endif; ?>
-->

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
<table class="table table-striped">
  <? foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <? endforeach; ?>
</table>
<? endif; ?>

  <!-- Button to Open the Modal -->
<!--
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mustBeLoggedInFirst">
    Open modal
  </button>
-->

  <!-- The Modal -->
  <div class="modal" id="mustBeLoggedInFirst">
    <div class="modal-dialog">
      <div class="modal-content">
      
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title"></h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        
        <!-- Modal body -->
        <div class="modal-body" style="text-align:center">

          <h4>You must be logged in first.</h4>
          <div class="collapse navbar-collapse" id="header-collapse">
            <nav>
            <ul class="nav">
                <li id="loginOptions">
    <?=$this->context($this)->renderInContext('loginoptions.phtml', [ 'account' => $account ]); ?>
                </li>
            </ul>
            </nav>
          </div>

        </div>
        
        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
        
      </div>
    </div>
  </div>
