<? // get the 3 letter institution code //
  $inst = getenv('VUFIND_LIBRARY');

  // path to the individual institution customization variables//
  $configInclude =  "/usr/local/vufind/themes/$inst/config.php";

  // include individual institution customization file //
  if (file_exists($configInclude)) {
      include $configInclude;
  }

?>

<footer>
<div class="row">
  <div class="col-sm-3">
    <img src='/all/vf/themes/carli/images/ishare-footer-logo.png' class='img-responsive' />
    <p class='sm-text carlifoot'>I-Share includes the resources of 90 Illinois libraries that belong to the 
    <a href='https://www.carli.illinois.edu'>Consortium of Academic and Research Libraries in Illinois</a><br />&nbsp;</p>
    <p class='sm-text carlifoot'> 
     <a href="https://www.vpaa.uillinois.edu/resources/web_privacy">U of I Privacy Notice</a> | 
     <a href="https://www.carli.illinois.edu/web_privacy">CARLI Privacy Notice</a></p>
   
  </div>
  <div class="col-sm-3">
    <h3><?=$this->transEsc('Search Options')?></h3>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
      <li>
          <a href='https://i-share.carli.illinois.edu/<? echo $inst; ?>'>Classic Search</a>
        </li>
    </ul>
<!--
    <h3><?=$this->transEsc('Need Help?')?></h3>
-->
    <ul>
      <li><a href="<?=$this->url('help-home')?>?topic=search" class="help-link"><?=$this->transEsc('Search Tips')?></a></li>
<!--
      <li><a href="#"><?=$this->transEsc('Ask a Librarian')?></a></li>
      <li><a href="#"><?=$this->transEsc('FAQs')?></a></li>
-->
    </ul>
  </div>
  <div class="col-sm-3">
    <h3><?=$this->transEsc('Find More')?></h3>
    <ul>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
<! CARLI BEGIN !>
<!-- Do not show alpha browse link if in UC  --!>
          <? if (!getenv('VUFIND_LIBRARY_IS_UC')): ?>
      <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
          <? endif; ?>
<!-- institution links for New Items and Course Reserves even if in /all/vf-xxx/ no links in /all/vf/ --!>          
          <? if (!empty($inst)) { ?>    
      <li><a href="/vf-<?print($inst)?>/Search/Reserves"><?=$this->transEsc('Course Reserves')?></a></li>
      <li><a href="/vf-<?print($inst)?>/Search/NewItem"><?=$this->transEsc('New Items')?></a></li>
          <? } ?>
<! CARLI END !>
<!--
        <? if (!empty($courseReservesUrl)) { ?>
        <li>
          <a href='<? echo $courseReservesUrl; ?>'>Course Reserves</a>
        </li>
        <? } ?>
<! CARLI BEGIN work arounds for NI !>
        <? if (!empty($newItemsUrl)) { ?>
        <li>
          <a href='<? echo $newItemsUrl; ?>'>New Items</a>
        </li>
        <? } ?>
<! CARLI END work arounds for NI !>
-->
    </ul>
  </div>
  <div class="col-sm-3">
    <h3>About CARLI</h3>
    <ul>
      <li><a href="https://www.carli.illinois.edu/products-services/i-share">About I-Share</a></li>
      <li><a href="https://www.carli.illinois.edu/membership/i-share_part">List of I-Share Libraries</a></li>
      <li><a href="https://www.carli.illinois.edu/membership/mem-libs/ishare-map">Map of I-Share Libraries</a></li>
    </ul>
  </div>
  </div> 
</footer>
