<! CARLI BEGIN Customization !>
<? // CARLI customization information //

	// get the 3 letter institution code //
	$inst = getenv('VUFIND_LIBRARY');

	// path to the individual institution customization variables//
	$configInclude =  "/usr/local/vufind/themes/$inst/config.php";

	// Setenv VUFIND_LIBRARY_BASE_PATH /all/vf-uiu
	$is_uc = getenv('VUFIND_LIBRARY_IS_UC');
  
	// include individual institution customization file //
	if (file_exists($configInclude)) {
		include $configInclude;
	}

?>
<! CARLI END Customization !>

<? $account = $this->auth()->getManager(); ?>
<div class="banner container navbar">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
      <span class="sr-only">Toggle navigation</span>
      <i class="fa fa-bars" aria-hidden="true"></i>
    </button>
<!-- CARLI COMMENT OUT BEGIN
    <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>">VuFind</a>
CARLI COMMENT OUT END -->
  </div>
  <? if (!isset($this->layout()->renderingError)): ?>
    <div class="collapse navbar-collapse" id="header-collapse">
      <nav>
        <ul role="navigation" class="nav navbar-nav navbar-right flip">
          <? if ($this->feedback()->tabEnabled()): ?>
            <li>
              <a id="feedbackLink" data-lightbox href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope" aria-hidden="true"></i> <?=$this->transEsc("Feedback")?></a>
            </li>
          <? endif; ?>
          <? $cart = $this->cart(); if ($cart->isActive()): ?>
            <li id="cartSummary">
              <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>">
                <i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?>
                <span class="full<?=!$cart->isFull() ? ' hidden' : '' ?>">(<?=$this->transEsc('bookbag_full') ?>)</span>
              </a>
            </li>
          <? endif; ?>
          <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>"><i class="fa fa-home" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
            </li>
            <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
              <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
            </li>
            <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
              <? if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
              <? else: ?>
<! CARLI BEGIN Customization !>
<? if (isset($loginButtonText)) : ?>
				<a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <? echo $loginButtonText ?></a>
				<? if (isset($loginLinkHelp)) : ?>
					<? echo '<span class="loginLinkHelp"><a href="/vf-' . $inst . '/MyResearch/UserLogin?auth_method=ILS">' . $loginLinkHelp . '</a></span>' ?>
				<? endif; ?>
<? else: ?>           
                <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
<? endif; ?>
<! CARLI END Customization !>             
              <? endif; ?>
            </li>
          <? endif; ?>

          <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
            <li class="theme dropdown">
              <form method="post" name="themeForm" id="themeForm">
                <input type="hidden" name="ui"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->themeOptions as $current): ?>
                  <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>

          <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
            <li class="language dropdown">
              <form method="post" name="langForm" id="langForm">
                <input type="hidden" name="mylang"/>
              </form>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                  <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
                <? endforeach; ?>
              </ul>
            </li>
          <? endif; ?>
        </ul>
      </nav>
    </div>
  <? endif; ?>

<! CARLI BEGIN Customization !>
<?
	// if in the UC do not display custom header //
	if ($is_uc) {
		echo '<a class="navbar-brand lang-' . $this->layout()->userLang . '" href="' . $this->url('home') . '">VuFind</a>';
	} else {	
	// if there is a custom header image show, otherwise show the defalt CARLI logo //
	if (isset($headerImage)) {
	    // H1 needed for accessabilty //
	  	echo '<h1 class="hidden">VuFind ';
			if (preg_match('/vf-(...)/', $this->url('home'), $matches)) {
				$this->libname = $matches[1];
			}
		echo $this->translate($this->libname);
		echo '</h1>';
		if (!empty($headerUrl)) {
    		echo '<a class="lang-' . $this->layout()->userLang . '" href="' . $headerUrl . '"><img src="/all/vf-' . $inst . '/themes/' . $inst . '/images/' . $headerImage . '"></a>';
		} elseif (!empty($headerMap)) {
			echo '<img src="/all/vf-' . $inst . '/themes/' . $inst . '/images/' . $headerImage . '" usemap="#Map" alt="VuFind Search page ' . $this->translate($this->libname) .'">';
			echo '<map name="Map" id="Map">';
			echo $headerMap;
			echo '</map>';
		} else {
			echo '<a class="lang-' . $this->layout()->userLang . '" href="' . $this->url('home') . '"><img src="/all/vf-' . $inst . '/themes/' . $inst . '/images/' . $headerImage . '"></a>';
		}
	} else {
		echo '<a class="navbar-brand lang-' . $this->layout()->userLang . '" href="' . $this->url('home') . '">VuFind</a>';
		if (! $is_uc) {
			echo '<h1>';
			if (preg_match('/vf-(...)/', $this->url('home'), $matches)) {
				$this->libname = $matches[1];
			}
			echo $this->translate($this->libname);
			echo '</h1>';
		}
	}
}
?>
<! call from image-map.js for the image map javascript to resize maps for responsivness  !>
<script>
	$('img[usemap]').imageMap();
</script>
<! CARLI END Customization !>

</div>
<? if ($this->layout()->searchbox !== false): ?>
  <div class="search container navbar">
    <nav class="nav searchbox hidden-print">
      <?=$this->layout()->searchbox ?>
    </nav>
  </div>
<? endif; ?>
