<?
  // Set up page title:
  $this->headTitle($this->translate('Checked Out Items'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<!-- CARLI EDIT: sort support -->
<?
// https://defuse.ca/blog/escaping-string-literals-for-javascript-in-php.html
function js_string_escape($data)
{
    $safe = "";
    for($i = 0; $i < strlen($data); $i++)
    {
        if(ctype_alnum($data[$i]))
            $safe .= $data[$i];
        else
            $safe .= sprintf("\\x%02X", ord($data[$i]));
    }
    return $safe;
}

$sortScript = <<<JS
var result_selector = '.result';
var item_count = 0;
var items_per_page = 50;
var all_items;

function collectAllItems() {
  all_items = \$('.result').toArray();
  item_count = all_items.length;
}

function getListItems() {
    var selector = result_selector;
    var \$parentObj = \$(selector).parent();
    var \$childrenObjs = \$parentObj.children(\$(selector));
    return \$childrenObjs;
}

function setListItems(thisPage) {
    var selector = result_selector;
    var \$parentObj = \$(selector).parent();
    var \$childrenObjs = \$parentObj.children(\$(selector));
    \$childrenObjs.detach();
    var fromRecords = (thisPage-1)*items_per_page;
    var toRecords = (thisPage-1)*items_per_page+items_per_page;
    \$(all_items).slice(fromRecords, toRecords).appendTo(\$parentObj);
    createPageControl(thisPage, fromRecords+1, toRecords);
    // clear out the Select Page checkbox
    \$('.checkbox-select-all').removeAttr('checked');
    \$('.checkbox-select-item').removeAttr('checked');

}

function createPageControl(thisPage, from, to) {
    // set the form hidden field
    \$('#pageNumber').val(thisPage);

    if (items_per_page > item_count) return;

    var numPages = Math.floor(item_count / items_per_page);
    if (item_count % items_per_page !== 0) numPages++;

    if (to > item_count) to = item_count;
    var showingThisMany = 'Showing <strong>' + from + ' - ' + to + '</strong> of <strong>' + item_count + '</strong> Items    ';
    $('.showing_items').html(showingThisMany);

    var pageControl = '';

    if (thisPage === 1) {
        pageControl +=
            '<!-- Previous page link --> ' + "\\n" + 
            '<li class="disabled"> <span>« Prev</span> ' + "\\n" + 
                '</li> ' + "\\n";

        pageControl +=
            '<!-- First page link --> ' + "\\n" + 
            '<li class="disabled"> <span>First</span> ' + "\\n" + 
                '</li> ' + "\\n";

    } else {
        pageControl +=
            '<!-- Previous page link --> ' + "\\n" + 
            '<li>' + "\\n" +
                '<a href="#" onClick="setListItems(' + (thisPage-1) + ')">' + "\\n" +
            '« Prev      </a>' + "\\n" +
            '</li>' + "\\n";

        pageControl +=
            '<!-- First page link --> ' + "\\n" + 
            '<li>' + "\\n" + 
                '<a href="#" onClick="setListItems(1)">' + "\\n" + 
            'First      </a>' + "\\n" + 
            '</li>' + "\\n";
    }

    for (var i=1; i <= numPages; i++) {

        if (thisPage === i) {
            pageControl +=
                '<!-- Numbered page links --> ' + "\\n" + 
                '<li class="active"> <span>' + i + '</span> ' + "\\n" + 
                '</li> ' + "\\n";
        } else {
            pageControl +=
                '<li> ' + "\\n" + 
                      '<a href="#" onClick="setListItems(' + i + ')"> ' + "\\n" + 
                i +
                '        </a> ' + "\\n" + 
                '</li> ' + "\\n";
        }
    }

    if (thisPage === numPages) {
        pageControl +=
            '<!-- Last page link --> ' + "\\n" + 
            '<li class="disabled"> <span>Last</span>' + "\\n" +
            '</li>' + "\\n" +

            '<!-- Next page link --> ' + "\\n" + 
            '<li class="disabled"> <span>Next »</span>' + "\\n" + 
            '</li>' + "\\n";

    } else {
        pageControl +=
            '<!-- Last page link --> ' + "\\n" + 
            '<li> ' + "\\n" + 
                    '<a href="#" onClick="setListItems(' + numPages + ')"> ' + "\\n" + 
                'Last      </a> ' + "\\n" + 
                '</li> ' + "\\n" + 

            '<!-- Next page link --> ' + "\\n" + 
            '<li> ' + "\\n" + 
                    '<a href="#" onClick="setListItems(' + (thisPage+1) + ')"> ' + "\\n" + 
                'Next &gt; ' + "\\n" + 
              '</a> ' + "\\n" + 
                '</li> ' + "\\n";
    }

    $('.pagination').html(pageControl);
}

function sortResults(sortBy, sortBy2, sortBy3) {
    all_items.sort(function(a,b){
        var aVal = a.getAttribute('data-' + sortBy + '-sort');
        var bVal = b.getAttribute('data-' + sortBy + '-sort');
        if (aVal === null || bVal === null) {
          return 0;
        }
        if (sortBy2 != null) {
          var aSortBy2val = a.getAttribute('data-' + sortBy2 + '-sort');
          var bSortBy2val = b.getAttribute('data-' + sortBy2 + '-sort');
          aVal += aSortBy2val;
          bVal += bSortBy2val;
        }
        if (sortBy3 != null) {
          var aSortBy3val = a.getAttribute('data-' + sortBy3 + '-sort');
          var bSortBy3val = b.getAttribute('data-' + sortBy3 + '-sort');
          aVal += aSortBy3val;
          bVal += bSortBy3val;
        }
        return aVal.localeCompare(bVal);
    });
    setListItems(1);

    // set the form hidden field
    \$('#sortBy').val(sortBy);
}

\$(document).ready(function(){
  collectAllItems();
  setListItems(\$('#pageNumber').val());
JS;

$sortScript .= "\n  var sortBy = '" . js_string_escape(array_key_exists('sortBy', $_POST) ? $_POST['sortBy'] : "") . "';\n";

$sortScript .= <<<JS
  \$('select[id=sort_chargeditems_options_1]').change(function(){
    \$('select[id=sort_chargeditems_options_1] option:selected').each(function() {
      var sortBy = \$(this).val();
      if (sortBy === "duedate") {
        sortResults('duedate', 'library', 'title');
      } else if (sortBy == "library") {
        sortResults('library', 'duedate', 'title');
      } else if (sortBy == "title") {
        sortResults('title', null, null);
      }
    });
  });

/************************
  This is done on the server now:
  if (sortBy === "duedate") {
    \$('select[id=sort_chargeditems_options_1]').val(sortBy).trigger('change');
  } else if (sortBy === "title") {
    \$('select[id=sort_chargeditems_options_1]').val(sortBy).trigger('change');
  } else if (sortBy === "library") {
    \$('select[id=sort_chargeditems_options_1]').val(sortBy).trigger('change');
  }
*************************/

});

JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $sortScript, 'SET'); ?>
<!-------------------------------->

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Checked Out Items')?></h2>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <? if (!empty($this->transactions)): ?>

    <? if ($this->renewForm): ?>
    <form name="renewals" method="post" id="renewals">
<!-- CARLI EDIT: added 'sortby' hidden field -->
<input type="hidden" id="sortBy" name="sortBy" value="<?=array_key_exists('sortBy', $_POST) ? $_POST['sortBy'] : "duedate"?>">
<input type="hidden" id="pageNumber" name="pageNumber" value="<?=array_key_exists('pageNumber', $_POST) ? $_POST['pageNumber'] : "1"?>">
      <div class="toolbar">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
            <?=$this->transEsc('select_page')?>
          </label>
          <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
          <!-- CARLI EDIT: only show "renew all" if fewer than 51 items total -->
          <? if (count($this->transactions) < 51): ?>
          <input type="submit" class="btn btn-default" id="renewAll" name="renewAll" value="<?=$this->transEsc('renew_all')?>" />
          <? endif; ?>
        </div>
      </div>
    <? endif; ?>

    <!-- CARLI EDIT: placeholder for showing x of y items -->
    <div class="showing_items"></div>

    <? if ($paginator): ?>
      <?
        $end = min(
          $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage()),
          $paginator->getTotalItemCount()
        );
        $transParams = [
          '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
          '%%end%%'   => $this->localizedNumber($end),
          '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount())
        ];
      ?>
      <?=$this->translate('showing_items_of_html', $transParams); ?>
    <? endif; ?>

    <? foreach ($hiddenTransactions as $ilsDetails): ?>
      <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
        <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
        <? $prefix = isset($ilsDetails['title']) ? $ilsDetails['title'] : $ilsDetails['item_id']; ?>
        <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
          <div class="alert alert-success"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></div>
        <? else: ?>
          <div class="alert alert-danger"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
        <? endif; ?>
      <? endif; ?>
      <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
        <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
        <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
      <? endif; ?>
    <? endforeach; ?>

<!-- CARLI EDIT: add "sort by" controls -->
<div class="container-fluid">
  <div class="form-inline">
    <div class="pull-right">
      <label for="sort_chargeditems_options_1">Sort</label>
      <select id="sort_chargeditems_options_1" name="sort_chargeditems" class="jumpMenu form-control">
          <option value="duedate"<?=array_key_exists('sortBy', $_POST) && $_POST['sortBy'] == 'duedate' ? 'selected="selected"'  : ''?>>Due Date</option>
          <option value="title"<?=array_key_exists('sortBy', $_POST) && $_POST['sortBy'] == 'title' ? 'selected="selected"'  : ''?>>Title</option>
          <option value="library"<?=array_key_exists('sortBy', $_POST) && $_POST['sortBy'] == 'library' ? 'selected="selected"'  : ''?>>Library</option>
      </select>
    </div>
  </div>
</div>
<!----------------------------------------->

    <!-- CARLI EDIT: surround transactions with a container; necessary for sorting! -->
    <div id="carli-sort-container">
    <? $i = 0; foreach ($this->transactions as $resource): ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <!-- CARLI EDIT: add sortable data: duedate, title, library -->
      <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="result" data-duedate-sort="<?=$this->escapeHtmlAttr($ilsDetails['duedate_sort'])?>" data-title-sort="<?=$this->escapeHtmlAttr($ilsDetails['title'])?>" data-library-sort="<?=$this->escapeHtmlAttr($ilsDetails['institution_name'])?>" data-titlesort="<?=$this->escapeHtmlAttr($ilsDetails['title'])?>">
        <? if ($this->renewForm): ?>
          <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
            <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
            <div class="checkbox">
              <label>
                <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
              </label>
              <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
              <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
            </div>
          <? endif; ?>
        <? endif; ?>

        <?
          $coverDetails = $this->record($resource)->getCoverDetails('checkedout', 'small', $this->recordLink()->getUrl($resource));
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
              <?=$cover ?>
            </div>
            <? $thumbnail = ob_get_contents(); ?>
          <? ob_end_clean(); ?>
        <? endif; ?>
        <div class="media">
          <? if ($thumbnail && $thumbnailAlignment == 'left'): ?>
            <?=$thumbnail ?>
          <? endif ?>
          <div class="media-body">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource) .
                  '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>
            <? if (count($resource->getFormats()) > 0): ?>
              <?=$this->record($resource)->getFormatList() ?>
              <br/>
            <? endif; ?>
            <? if (!empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('location_' . $ilsDetails['institution_name'], [], $ilsDetails['institution_name'])?></strong>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['borrowingLocation'])): ?>
              <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], [], $ilsDetails['borrowingLocation'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['renew'])): ?>
              <strong><?=$this->transEsc('Renewed')?>:</strong> <?=$this->transEsc($ilsDetails['renew'])?>
              <? if (isset($ilsDetails['renewLimit'])): ?>
                / <?=$this->transEsc($ilsDetails['renewLimit'])?>
              <? endif; ?>
              <br />
            <? endif; ?>

            <? $showStatus = true; ?>

            <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
              <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
              <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                <? $showStatus = false; ?>
                <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($renewDetails['new_date'])?> <? if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><? endif; ?></strong>
                <div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
              <? else: ?>
                <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
                <div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><? if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><? endif; ?></div>
              <? endif; ?>
            <? else: ?>
              <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?></strong>
              <? if ($showStatus): ?>
                <? if (isset($ilsDetails['dueStatus']) && preg_match('/[Oo]verdue/', $ilsDetails['dueStatus'])): ?>
                  <div class="alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
                <? endif; ?>
              <? endif; ?>
            <? endif; ?>

            <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
              <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
              <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
            <? endif; ?>
          </div>
          <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <? endif ?>
        </div>
      </div>
    <? endforeach; ?>
    <!-- CARLI EDIT: surround transactions with a container; necessary for sorting! -->
    </div> <!-- id="carli-sort-container" -->

  <!-- CARLI EDIT: our own custom client-side pagination -->
  <ul class="pagination">
  </ul>



    <? if ($this->renewForm): ?></form><? endif; ?>
    <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml') : ''?>
  <? else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
</div>
