<?
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Only display home library form if we have multiple pickup locations:
    //$showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);
    // No, *always* show becuase patron may wish to change pickup library****  (isset($this->pickup) && count($this->pickup) > 1);
    $showHomeLibForm = true;

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Profile')?></h2>
  <?=$this->flashmessages();?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<!-- CARLI edit -->
        <!-- <form id="profile_form" class="form-inline" method="post"> -->
        <form id="ILLRequestForm" class="form-inline" method="post">
<!-- end of CARLI edit -->

  <table class="table table-striped">
    <?
      echo $this->renderArray(
        $arrTemplate, $this->profile,
        [
          $this->transEsc('First Name') => 'firstname',
          $this->transEsc('Last Name') => 'lastname'
        ]
      );
     ?>
    <? if ($showHomeLibForm): ?>
<!-- CARLI added: -->
  <? if (!empty($this->pickupLibraries)): ?>
      <tr><th><?=$this->transEsc('Preferred Pick Up Library')?>:</th>

      <td>

    <div class="form-group">
      <? if (count($this->pickupLibraries) > 0): ?>
        <select id="pickupLibrary" name="pickupLibrary" class="form-control">
        <?
          if (isset($this->actualHomeLibrary) && $this->actualHomeLibrary !== "") {
              $selected = $this->actualHomeLibrary;
          } else {
              $selected = false;
          }
        ?>
        <? foreach ($this->pickupLibraries as $lib): ?>
          <option value="<?=$this->escapeHtmlAttr($lib['id'])?>"<?=(($selected === false && isset($lib['isDefault']) && $lib['isDefault']) || $selected === $lib['id']) ? ' selected="selected"' : ''?>>
            <?=$this->transEsc('library_' . $lib['name'], null, $lib['name'])?>
          </option>
        <? endforeach; ?>
        </select>
      <? else: ?>
        <? $lib = $this->pickupLibraries[0]; ?>
        <input type="text" class="form-control" size="40" readonly="readonly" value="<?=$this->escapeHtmlAttr($this->translate('library_' . $lib['name'], null, $lib['name']))?>" />
        <input type="hidden" id="pickupLibrary" name="pickupLibrary" value="<?=$this->escapeHtmlAttr($lib['id'])?>" />
      <? endif; ?>
    </div>
  <? endif; ?>


      </td>
      </tr>
<!-- end of CARLI added -->

      <tr><th><?=$this->transEsc('Preferred Pick Up Location')?>:</th>
      <?
        $selected = (isset($this->profile['home_library']) && $this->profile['home_library'] != "")
            ? $this->profile['home_library'] : $this->defaultPickupLocation
      ?>

      <td>
          <!-- <select id="home_library" name="home_library" class="form-control"> -->
          <select id="pickupLibraryLocation" name="home_library" class="form-control">
            <? foreach ($this->pickup as $lib): ?>
              <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->transEsc('location_' . $lib['locationDisplay'], null, $lib['locationDisplay'])?></option>
            <? endforeach; ?>
          </select>
          <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Save')?>" />
      </td>
    <? endif; ?>
    <?
      echo $this->renderArray(
        $arrTemplate, $this->profile,
        [
          $this->transEsc('Email') => 'email',
          $this->transEsc('Address') . ' 1' => 'address1',
          $this->transEsc('Address') . ' 2' => 'address2',
          $this->transEsc('Zip') => 'zip',
          $this->transEsc('City') => 'city',
          $this->transEsc('Country') => 'country',
          $this->transEsc('Phone Number') => 'phone',
          $this->transEsc('Group') => 'group',
          $this->transEsc('Expires') => 'expiration_date'
        ]
      );
    ?>
  </table>
        </form>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile'])?>
</div>

<!-- CARLI added: -->
<?
    // Set up ill script; we do this inline instead of in the header for lightbox compatibility:
    $this->inlineScript()->appendFile('ill.js');

    $js = <<<JS
        if ($.isReady) {
            setUpILLRequestForm('');
        } else {
            $(document).ready(function(){
                setUpILLRequestForm('');
            });
        }
JS;

    echo $this->inlineScript()->appendScript($js);
?>
