<div class="form-group">
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
<!-- CARLI BEGIN change type from "text" to "password" -->
  <input type="password" name="username" id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
<!-- CARLI END change type from "text" to "password" -->
</div>
<div class="form-group">
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
<!-- CARLI BEGIN change type from "password" to "text" -->
  <input type="text" name="password" id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" class="form-control"/>
<!-- CARLI END change type from "password" to "text" -->
</div>
