<!-- CARLI BEGIN Customization --!>
<?php // CARLI customization information //

  // get the 3 letter institution code //
  $inst = getenv('VUFIND_LIBRARY');

  // path to the individual institution customization variables//
  $configInclude =  "/usr/local/vufind/themes/$inst/config.php";

  // Setenv VUFIND_LIBRARY_BASE_PATH /all/vf-uiu
  $is_uc = substr(getenv('VUFIND_LIBRARY_BASE_PATH'), 0, 5) === "/all/";
  if (! $is_uc) {

      // include individual institution customization file //
      if (file_exists($configInclude)) {
          include $configInclude;
      }
  }
?>
<!-- CARLI END Customization --!>

<!-- CARLI: BEGIN comment out library selection control
<div class="form-group">
  <label class="control-label" for="login_target"><?=$this->transEsc('login_target')?>:</label>
  <?$currentTarget = $this->request->get('target'); if (!$currentTarget) $currentTarget = $this->auth()->getManager()->getDefaultLoginTarget();?>
  <select id="login_target" name="target" class="form-control">
    <?foreach ($this->auth()->getManager()->getLoginTargets() as $target):?>
      <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target == $currentTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
    <? endforeach ?>
  </select>
</div>
CARLI: END comment out library selection control -->

<!-- CARLI BEGIN hidden target --!>
<input type="hidden" name="target" value="<?=getenv('VUFIND_LIBRARY_DB')?>"/>
<!-- CARLI END hidden target --!>

<!-- CARLI BEGIN Customization --!>
<?php
  // if there is a custom login text for an institution //
  if (isset($loginText)) {
    echo $loginText;
  }
?>
<!-- CARLI END Customization --!>

<div class="form-group">
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
  <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" type="text" name="username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
</div>
<div class="form-group">
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
  <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" type="password" name="password" class="form-control"/>
</div>
