<!--
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ====> Page begins: themes/carli/templates/Auth/MultiILS/loginfields.phtml ====><br>
-->
<!-- CARLI BEGIN Customization --!>
<?php // CARLI customization information //

  // get the 3 letter institution code //
  $inst = getenv('VUFIND_LIBRARY');

  // path to the individual institution customization variables//
  $configInclude =  "/usr/local/vufind/themes/$inst/config.php";

  // include individual institution customization file //
  if (file_exists($configInclude)) {
      include $configInclude;
  }
?>
<!-- CARLI END Customization --!>

<!-- CARLI: BEGIN comment out library selection control
<div class="form-group">
  <label class="control-label" for="login_target"><?=$this->transEsc('login_target')?>:</label>
  <?$currentTarget = $this->request->get('target'); if (!$currentTarget) $currentTarget = $this->auth()->getManager()->getDefaultLoginTarget();?>
  <select id="login_target" name="target" class="form-control">
    <?foreach ($this->auth()->getManager()->getLoginTargets() as $target):?>
      <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target == $currentTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
    <? endforeach ?>
  </select>
</div>
CARLI: END comment out library selection control -->

<!-- CARLI BEGIN hidden target --!>
<input type="hidden" name="target" value="<?=getenv('VUFIND_LIBRARY_DB')?>"/>
<!-- CARLI END hidden target --!>

<!-- CARLI BEGIN Customization --!>
<?php
  // if there is a custom login text for an institution //
  if (isset($loginText)) {
    echo $loginText;
  }
?>
<!-- CARLI END Customization --!>

<div class="form-group">
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
<!-- CARLI BEGIN change type from "text" to "password" -->
  <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" type="password" name="username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
<!-- CARLI END change type from "text" to "password" -->
</div>
<div class="form-group">
  <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
<!-- CARLI BEGIN change type from "password" to "text" -->
  <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" type="text" name="password" class="form-control"/>
<!-- CARLI END change type from "password" to "text" -->
</div>
<!--
<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <==== Page ends: themes/carli/templates/Auth/MultiILS/loginfields.phtml <====<br>
-->
