<fieldset class="carliAdvancedVersion">
    <legend>Version</legend>
    <div class="carliAdvancedVersion">
        <input class="carliformats" type="radio" name="" value="" id="AnyVersion">
        <label for="AnyVersion">Any Version</label>
    </div>
    <div class="carliAdvancedVersion">
        <input class="carliformats" type="radio" name="" value="" id="FormatElectronic">
        <label for="FormatElectronic">Electronic</label>
    </div>
    <div class="carliAdvancedVersion">
        <input class="carliformats" type="radio" name="" value="" id="FormatElectronicOrPrint">
        <label for="FormatElectronicOrPrint">Electronic or Print, anything but microform</label>
    </div>
    <div class="carliAdvancedVersion">
        <input class="carliformats" type="radio" name="" value="" id="FormatPrint">
        <label for="FormatPrint">Print, neither electronic nor microform</label>
    </div>
    <div class="carliAdvancedVersion">
        <input class="carliformats" type="radio" name="" value="" id="FormatMicroform">
        <label for="FormatMicroform">Microform</label>
    </div>

    <script>
var selectedVersion = null;
var allFormats = [];
$(document).ready(function() {
    $('#limit_format option').each(function(index,element){
      allFormats.push(element.value);
    });

    $(".carliformats").click(function() {
      selectedVersion = this.id;

      // make anonymous radio buttons behave correctly
      $(".carliformats").each(function() {
        if ( this.id == selectedVersion ) {
            this.checked = true;
        }
        else {
            this.checked = false;
        };
      });

      $("#ExcludeElectronic").prop('checked', false);
      $("#ExcludeMicroform").prop('checked', false);
      var fmts = [];
      if (selectedVersion === "FormatElectronic") {
        fmts.push("~format:\"Electronic\"");
      } else if (selectedVersion === "FormatElectronicOrPrint") {
        $("#ExcludeMicroform").prop('checked', true);
      } else if (selectedVersion === "FormatPrint") {
        $("#ExcludeElectronic").prop('checked', true);
        $("#ExcludeMicroform").prop('checked', true);
      } else if (selectedVersion === "FormatMicroform") {
        fmts.push("~format:\"Microform\"");
      }
      $("#limit_format").val(fmts);

    });    

    $('#ExcludeElectronic').change(function() {
      $("#AnyVersion").prop('checked', false);
      $("#FormatElectronic").prop('checked', false);
      $("#FormatElectronicOrPrint").prop('checked', false);
      $("#FormatPrint").prop('checked', false);
      $("#FormatMicroform").prop('checked', false);

      if($('#ExcludeElectronic').prop('checked') && $('#ExcludeMicroform').prop('checked')) {
        $('#FormatPrint').prop('checked', true);
      } else if ($('#ExcludeMicroform').prop('checked')) {
        $('#FormatElectronicOrPrint').prop('checked', true);
      }
    });
    $('#ExcludeMicroform').change(function() {
      $("#AnyVersion").prop('checked', false);
      $("#FormatElectronic").prop('checked', false);
      $("#FormatElectronicOrPrint").prop('checked', false);
      $("#FormatPrint").prop('checked', false);
      $("#FormatMicroform").prop('checked', false);

      if($('#ExcludeElectronic').prop('checked') && $('#ExcludeMicroform').prop('checked')) {
        $('#FormatPrint').prop('checked', true);
      } else if ($('#ExcludeMicroform').prop('checked')) {
        $('#FormatElectronicOrPrint').prop('checked', true);
      }
    });

});
    </script>
</fieldset>

