    <script>
var selectedVersion = null;
$(document).ready(function() {
  setStateOfCarliControls();
  $('#ExcludeElectronic').change(function() {
    setStateOfCarliControls();
  });
  $('#ExcludeMicroform').change(function() {
    setStateOfCarliControls();
  });
  $('#limit_format').change(function() {
    setStateOfCarliControls();
  });
});
function setStateOfCarliControls() {
  // Give precedence to Format selected
  // Conflict? Remove the Exclude button
  var options = $('#limit_format option:selected');
  var values = $.map(options ,function(option) {
    return option.value;
  });
  var gotMicroform = false;
  var gotElectronic = false;
  var len = values.length;
  for (var i=0; i<len; i++) {
     if (values[i] === '~format:"Electronic"') {
        gotElectronic = true;
        if ($('#ExcludeElectronic').prop('checked')) {
          $('#ExcludeElectronic').prop('checked', false)
          alert('You cannot "Exclude Electronic" and select "Electronic" Format at the same time.');
        }
     } else if (values[i] === '~format:"Microform"') {
        gotMicroform = true;
        if ($('#ExcludeMicroform').prop('checked')) {
          $('#ExcludeMicroform').prop('checked', false)
          alert('You cannot "Exclude Microform" and select "Microform" Format at the same time.');
        }
     }
  }
}
    </script>

